config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'
  devise_for :teams
  root "teams#top"
  get '/' => 'teams#show', as: :signin
  resources :teams, only: [:index, :show, :edit, :update, :destroy], param: :team_url do
    collection do
      get 'search'
    end
    member do
      get 'stat'
      get 'ranking'
    end
    resources :players
    resources :games do
      resources :batting_stats, only: [:new, :create]
      resources :pitching_stats, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small mt-3 pt-4" style="background-color: sandybrown;">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Takahiro-Awaji</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: sandybrown;">
    <% if team_signed_in? %>
      <%= link_to image_tag('logo.jpg', class: "logo rounded"), team_path(current_team.team_url) %>
    <% else %>
      <%= link_to image_tag('logo.jpg', class: "logo rounded"), root_path %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <div class="nav-item btn">
        <%= link_to "チーム一覧", teams_path, class: "btn" %>
      </div>

      <% if team_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_team.team_name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "マイページ", team_path(current_team.team_url), class: "btn dropdown-item"%>
            <%= link_to "新規選手登録", new_team_player_path(current_team.team_url), class: "btn dropdown-item" %>
            <%= link_to "新規試合結果登録", new_team_game_path(current_team.team_url), class: "btn dropdown-item" %>
            <%= link_to "ランキング", ranking_team_path(current_team.team_url), class: "btn dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "ログアウト", destroy_team_session_path, method: :delete, class: "btn dropdown-item" %>
          </div>
        </li>
      </ul>
      <% else %>
         <ul class="navbar-nav mr-auto">
          <li class="btn nav-item"><%= link_to "新規チーム登録", new_team_registration_path, class: "new-team btn btn-primary" %></li>
          <li class="btn nav-item"><%= link_to "ログイン", team_session_path, class: "login btn btn-secondary" %></li>
        </ul>
      <% end %>

      <%= form_with(url: search_teams_path, local: true, method: :get, class: "form-inline my-2 my-lg-0 mr-3") do |form| %>
        <%= form.text_field :keyword, class: "form-control mr-sm-3 ", placeholder: "チーム名を入力してください", style: "width: 300px" %>
        <%= form.submit "検索", class: "btn btn-success my-2 my-sm-0"%>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_second_header.html.erb
<header class="top-page-header">
<h1><%= link_to image_tag('logo.jpg', class: "logo"), root_path %></h1>
 <div class="top-page-menu">
    <div class="row second-search">
      <%= form_with(url: search_teams_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, class: "second-search-form", placeholder: "チーム名を入力してください" %>
        <%= form.submit "検索", class: "btn btn-search"%>
      <% end %>
    </div>
    <div class="row second-team-index">
      <%= link_to "チーム一覧", teams_path, class: "btn btn-top-team-index" %>
    </div>
  <% if team_signed_in? %>
    <ul class="top-page-menu">
      <li><%= link_to "新規選手登録", new_team_player_path(@team), class: "btn btn-new-player" %></li>
      <li><%= link_to "新規試合結果登録", new_team_game_path(@team), class: "btn btn-new-game" %></li>
    </ul>
    <ul class="top-page-menu">
      <li><%= link_to "マイチームページ", team_path(current_team), class: "mypage btn btn-primary" %></li>
      <li><%= link_to "ログアウト", destroy_team_session_path, method: :delete, class: "logout btn btn-secondary" %></li>
    </ul>
  <% else %>
    <ul class="top-page-menu">
      <li><%= link_to "新規チーム登録", new_team_registration_path, class: "new-team btn btn-primary" %></li>
      <li><%= link_to "ログイン", team_session_path, class: "login btn btn-secondary" %></li>
    </ul>
  <% end %>
  </div>
</header>