config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'
  devise_for :teams
  root "teams#top"
  get '/' => 'teams#show', as: :signin
  resources :teams, only: [:index, :show, :edit, :update, :destroy], param: :team_url do
    collection do
      get 'search'
    end
    member do
      get 'stat'
      get 'ranking'
    end
    resources :players
    resources :games do
      resources :batting_stats, only: [:new, :create]
      resources :pitching_stats, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team
  has_many :players, through: :batting_stats, through: :pitching_stats
  has_many :batting_stats
  has_many :pitching_stats

  with_options presence: true do
    validates :gameday
    validates :opponent
    validates :total_stats_add
    validates :top_or_bottom
    validates :game_result
  end

  def self.search(search)
    if search != ''
      Game.where('opponent LIKE (?)', "%#{search}%")
    else
      Game.all
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_team
  before_action :set_game, only: [:show, :edit, :update]
  before_action :ensure_correct_team, except: [:index, :show, :search]
  before_action :search_game, only: [:index, :search]

  def index
    @games = Game.where(team_id: @team.id).page(params[:page]).per(10).order(gameday: :desc)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to team_game_path(@team.team_url, @game.id)
    else
      render 'new'
    end
  end

  def show
    @batting_stats = BattingStat.where(game_id: params[:id]).order(batting_order: :asc)
    @pitching_stats = PitchingStat.where(game_id: params[:id]).order(pitching_order: :asc)
  end

  def edit
  end

  def update
    if @game.update(game_params)
    else
      render 'edit'
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
  end

  def search
    # @s_games = Game.where(team_id: @team.id).search(params[:opponent_name]).page(params[:page]).per(10).order(gameday: :desc)
    @results = @g.result.where(team_id: @team.id).search(params[:opponent_name]).page(params[:page]).per(10).order(gameday: :desc)
  end

  private

  def set_team
    @team = Team.find_by!(team_url: params[:team_team_url])
  end

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:gameday, :gametime, :opponent, :tournament_name, :field_name,
                                 :game_attribute, :total_stats_add, :top_or_bottom, :game_myteam_score, :game_opponent_score,
                                 :game_result, :game_comment).merge(team_id: current_team.id)
  end

  def ensure_correct_team
    team = Team.find_by!(team_url: params[:team_team_url])
    redirect_to root_path if team != current_team
  end

  def search_game
    @g = Game.ransack(params[:q])
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/destroy.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <h2>削除が完了しました。</h2>
  <div class="row d-flex justify-content-around">
    <%= link_to "試合結果一覧へ戻る", team_games_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/games/index.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <div class="row d-flex justify-content-between">
    <h2>試合一覧</h2>
    <% if @team == current_team %>
      <%= link_to "試合結果登録", new_team_game_path(@team.team_url), class: "btn btn-info mb-2" %>
    <% end %>
  </div>

  <%= search_form_for @g, url: search_team_games_path, local: true, method: :get do |form| %>
    <div class="row my-3">
      <div class="col-md-3 col-sm-6 my-1 d-flex">
        <%= form.label :gameday_eq, "試合日" %>
        <%= form.date_field :gameday_eq, class: "form-control ml-2", style: "width: 70%;" %>
      </div>
      <div class="col-md-3 col-sm-6 my-1 d-flex">
        <%= form.label :game_attribute_eq, "試合区分" %>
        <%= form.select(:game_attribute_eq, ["公式戦", "練習試合", "その他"], {include_blank: "---"}, class: "ml-2", style: "width: 60%") %>
      </div>
      <%= form_with(url: search_team_games_path, local: true, method: :get) do |f| %>
      <div class="col-md-5 col-sm-10 my-1 d-flex">
        <%= f.label :opponent_name, "対戦相手" %>
        <%= f.text_field :opponent_name, class: "form-control ml-2", style: "width: 300px;" %>
      </div>
      <% end %>
      <div class="col-md-1 col-sm-2 my-1">
        <%= form.submit "検索", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

  <div class="col text-center">
    <%= paginate @games %>
    <div class="row">
      <table class="table text-nowrap">
        <thead class="thead-dark">
          <tr>
            <th scope="col" width="15%">試合日</th>
            <th scope="col" width="15%">試合区分</th>
            <th scope="col" width="40%">対戦相手</th>
            <th scope="col" width="10%">結果</th>
            <th scope="col" width="15%">スコア</th>
            <th scope="col" width="5%"></th>
          </tr>
        </thead>
        <tbody>
          <% @games.each do |game| %>
          <tr>
            <td class="position-relative"><%= link_to l(game.gameday, format: :default), team_game_path(@team.team_url, game.id), class: "stretched-link" %></td>
            <td><%= game.game_attribute %></td>
            <td><%= game.opponent %></td>
            <td class="text-nowrap">
            <% if game.game_result == "勝ち"%>
              <p class="d-inline p-2 bg-danger text-white rounded"><%= game.game_result %></p>
            <% elsif game.game_result == "負け"%>
              <p class="d-inline p-2 bg-primary text-white rounded"><%= game.game_result %></p>
            <% elsif game.game_result == "引き分け"%>
              <p class="d-inline p-2 bg-success text-white rounded"><%= game.game_result %></p>
            <% else %>
              <p class="d-inline p-2 bg-dark text-white rounded"><%= game.game_result %></p>
              <% end %>
            </td>
            <td><%= game.game_myteam_score %> - <%= game.game_opponent_score %></td>
            <td><%= link_to "詳細",team_game_path(@team.team_url, game.id), class: "btn btn-sm btn-secondary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @games %>
  </div>

  <div class="row d-flex justify-content-around">
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/games/new.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">
  <h2>試合結果登録</h2>

  <%= form_with(model: @game, url: team_games_path(@team.team_url), local: true) do |f| %>
    <%= render 'devise/shared/error_messages', resource: @game %>

    <div class="form-group row">
      <div class="col-sm-3">
        <%= f.label "試合日" %>
        <span class="ml-2 badge badge-danger">必須</span>
      </div>
      <%= f.date_field :gameday, class: "form-control col-sm-4" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "試合開始時間", class: "col-sm-3" %>
      <%= f.time_field :gametime, class: "form-control col-sm-4" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <div class="col-sm-3">
        <%= f.label "対戦相手" %>
        <span class="ml-2 badge badge-danger">必須</span>
      </div>
      <%= f.text_field :opponent, class: "form-control col-sm-6" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "大会名", class: "col-sm-3" %>
      <%= f.text_field :tournament_name, class: "form-control col-sm-6" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "球場名", class: "col-sm-3" %>
      <%= f.text_field :field_name, class: "form-control col-sm-6" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "試合区分", class: "col-sm-3" %>
      <%= f.select(:game_attribute, ["公式戦", "練習試合", "その他"], {include_blank: "選択してください"}, class: "col-sm-4 custom-select") %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <div class="col-sm-3">
        <%= f.label "通算成績に加える" %>
        <span class="ml-2 badge badge-danger">必須</span>
      </div>
      <div class="form-check">
        <label class="pr-2"><%= f.radio_button(:total_stats_add, 'はい', checked: true) %> はい</label>
        <label class="pr-2"><%= f.radio_button(:total_stats_add, 'いいえ') %> いいえ</label>
      </div>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <div class="col-sm-3">
        <%= f.label "スコア" %>
        <span class="ml-2 badge badge-danger">必須</span>
      </div>
      <div class="form-check">
        <label class="pr-2"><%= f.radio_button(:top_or_bottom, '先攻') %>先攻</label>
        <label class="pr-2"><%= f.radio_button(:top_or_bottom, '後攻') %>後攻</label>
        <div class="pt-2">
          自チーム <%= f.number_field :game_myteam_score, class: "score-form", style: "width: 50px;", min: 0 %> 　
          相手チーム <%= f.number_field :game_opponent_score, class: "score-form", style: "width: 50px;", min: 0 %>
        </div>
      </div>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <div class="col-sm-3">
        <%= f.label "試合結果" %>
        <span class="ml-2 badge badge-danger">必須</span>
      </div>
      <%= f.select(:game_result, ["勝ち", "負け", "引き分け", "その他"], {include_blank: "選択してください"}, class: "col-sm-4 custom-select") %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "コメント", class: "col-sm-3" %>
      <%= f.text_area :game_comment, class: "col-sm-6", rows: 8 %>
    </div>
    <hr width="80%" align="left">
    <div class="actions my-3 d-flex justify-content-center">
      <%= f.submit "登録する", class: "col-8 btn btn-primary" %>
    </div>
    
  <% end %>
  
  <div class="row d-flex justify-content-around">
    <%= link_to "試合結果一覧へ戻る", team_games_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/games/search.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <div class="row d-flex justify-content-between">
    <h2>試合一覧（検索結果）</h2>
    <% if @team == current_team %>
      <%= link_to "試合結果登録", new_team_game_path(@team.team_url), class: "btn btn-info mb-2" %>
    <% end %>
  </div>

  <%= search_form_for @g, url: search_team_games_path, local: true, method: :get do |form| %>
    <div class="row my-3">
      <div class="col-md-3 col-sm-6 my-1 d-flex">
        <%= form.label :gameday_eq, "試合日" %>
        <%= form.date_field :gameday_eq, class: "form-control ml-2", style: "width: 70%;", selected: params[:gameday] %>
      </div>
      <div class="col-md-3 col-sm-6 my-1 d-flex">
        <%= form.label :game_attribute_eq, "試合区分" %>
        <%= form.select(:game_attribute_eq, ["公式戦", "練習試合", "その他"], {include_blank: "---"}, class: "ml-2", style: "width: 60%;", selected: params[:game_attribute]) %>
      </div>
      <%= form_with(url: search_team_games_path, local: true, method: :get) do |f| %>
      <div class="col-md-5 col-sm-10 my-1 d-flex">
        <%= f.label :opponent_name, "対戦相手" %>
        <%= f.text_field :opponent_name, class: "form-control ml-2", style: "width: 300px;", value: params[:opponent_name] %>
      </div>
      <% end %>
      <div class="col-md-1 col-sm-2 my-1">
        <%= form.submit "検索", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

  <div class="col text-center">
    <%= paginate @results %>
    <div class="row">
      <table class="table text-nowrap">
        <thead class="thead-dark">
          <tr>
            <th scope="col" width="15%">試合日</th>
            <th scope="col" width="15%">試合区分</th>
            <th scope="col" width="40%">対戦相手</th>
            <th scope="col" width="10%">結果</th>
            <th scope="col" width="15%">スコア</th>
            <th scope="col" width="5%"></th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |game| %>
          <tr>
            <td class="position-relative"><%= link_to l(game.gameday, format: :default), team_game_path(@team.team_url, game.id), class: "stretched-link" %></td>
            <td><%= game.game_attribute %></td>
            <td><%= game.opponent %></td>
            <td class="text-nowrap">
            <% if game.game_result == "勝ち"%>
              <p class="d-inline p-2 bg-danger text-white rounded"><%= game.game_result %></p>
            <% elsif game.game_result == "負け"%>
              <p class="d-inline p-2 bg-primary text-white rounded"><%= game.game_result %></p>
            <% elsif game.game_result == "引き分け"%>
              <p class="d-inline p-2 bg-success text-white rounded"><%= game.game_result %></p>
            <% else %>
              <p class="d-inline p-2 bg-dark text-white rounded"><%= game.game_result %></p>
              <% end %>
            </td>
            <td><%= game.game_myteam_score %> - <%= game.game_opponent_score %></td>
            <td><%= link_to "詳細",team_game_path(@team.team_url, game.id), class: "btn btn-sm btn-secondary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @results %>
  </div>

  <div class="row d-flex justify-content-around">
    <%= link_to "試合一覧へ戻る", team_games_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/games/show.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <div class="row">
  <h2>試合結果詳細</h2>
  
    <% if @team == current_team %>
    <div class="btn-group">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="fas fa-pencil-alt fa-lg" style="color: darkblue"></span>
      </button>
      <div class="dropdown-menu">
        <%= link_to "編集", edit_team_game_path(@team.team_url), class: "dropdown-item" %>
        <%= link_to "削除", team_game_path(@team.team_url),class: "dropdown-item", method: :delete, data: {confirm: "本当に削除してもいいですか？"} %>
      </div>
    </div>
    <% end %>
  </div>

    <div class="col">

    <div class="row justify-content-center">
      <div class="p-2">
      <%= l(@game.gameday, format: :long) %>
      </div>
      <div class="p-2">
      <%= @game.gametime %>
      </div>
      <div class="p-2">
      <%= @game.field_name %>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="p-2">
      <%= @game.game_attribute %>
      </div>
      <div class="p-2">
      <%= @game.tournament_name %>
      </div>
    </div>

    <div class="row justify-content-center pt-3">
      <% if @game.top_or_bottom == "先攻"%>
      <h3 class="col-10 text-center">
        <span class="col-4">
          <%= @game.team.team_name %>
        </span>
        <span class="col-2">
          対
        </span>
        <span class="col-4">
          <%= @game.opponent %>
        </span>
      </h3>
      <% else %>
      <h3 class="col-10 text-center">
        <span class="col-4">
          <%= @game.opponent %>
        </span>
        <span class="col-2">
          対
        </span>
        <span class="col-4">
          <%= @game.team.team_name %>
        </span>
      </h3>
      <% end %>
    </div>

    <div class="row justify-content-center">
      <% if @game.top_or_bottom == "先攻" %>
      <h3 class="col-6 text-center">
        <span class="col-2">
          <%= @game.game_myteam_score %>
        </span>
        <span class="col-2">
          ー
        </span>
        <span class="col-2">
          <%= @game.game_opponent_score %>
        </span>
      </h3>
      <% else %>
      <h3 class="col-6 text-center">
        <span class="col-2">
          <%= @game.game_opponent_score %>
        </span>
        <span class="col-2">
          ー
        </span>
        <span class="col-2">
          <%= @game.game_myteam_score %>
        </span>
      </h3>
      <% end %>
    </div>

    <div class="text-center m-2">
      <% if @game.game_result == "勝ち"%>
        <h4 class="d-inline p-2 bg-danger text-white rounded"><%= @game.game_result %></h4>
      <% elsif @game.game_result == "負け"%>
        <h4 class="d-inline p-2 bg-primary text-white rounded"><%= @game.game_result %></h4>
      <% elsif @game.game_result == "引き分け"%>
        <h4 class="d-inline p-2 bg-success text-white rounded"><%= @game.game_result %></h4>
      <% else %>
        <h4 class="d-inline p-2 bg-dark text-white rounded"><%= @game.game_result %></h4>
      <% end %>
    </div>
    
    <div class="card mt-3">
      <div class="card-header">
      コメント：
      </div>
      <div class="card-body">
      <%= simple_format(@game.game_comment) %>
      </div>
    </div>

  </div>

  <div class="row col mt-3">
  <h3>選手個人成績</h3>
    
    <% if @team == current_team %>
    <div class="btn-group">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="fas fa-pencil-alt fa-lg" style="color: darkblue"></span>
      </button>
      <div class="dropdown-menu">
        <%= link_to "打者成績登録", new_team_game_batting_stat_path(@team.team_url, @game), class: "dropdown-item" %>
        <%= link_to "投手成績登録", new_team_game_pitching_stat_path(@team.team_url, @game), class: "dropdown-item" %>
      </div>
    </div>
    <% end %>
  

    <% if @batting_stats.present? %>
    <div class="overflow-auto">
    <h4 class="mt-4">打者成績</h4>
    <table class="table text-center text-nowrap">
    <thead class="thead-light">
      <tr>
        <th scope="col">背番号</th>
        <th scope="col">選手名</th>
        <th scope="col">出場</th>
        <th scope="col">打順</th>
        <th scope="col">守備位置</th>
        <th scope="col">打席</th>
        <th scope="col">打数</th>
        <th scope="col">安打</th>
        <th scope="col">打点</th>
        <th scope="col">得点</th>
        <th scope="col">盗塁</th>
        <th scope="col">二塁打</th>
        <th scope="col">三塁打</th>
        <th scope="col">本塁打</th>
        <th scope="col">三振</th>
        <th scope="col">四球</th>
        <th scope="col">死球</th>
        <th scope="col">犠打</th>
        <th scope="col">犠飛</th>
        <th scope="col">併殺</th>
        <th scope="col">敵失</th>
        <th scope="col">失策</th>
      </tr>
    </thead>
    <tbody>
      <% @batting_stats.each do |b| %>
      <tr>
        <td><%= b.player.number %></td>
        <td><%= link_to b.player.name, team_player_path(@team.team_url, b.player_id) %></td>
        <td><%= b.at_field %></td>
        <td><%= b.batting_order %></td>
        <td><%= b.fielding_position %></td>
        <td><%= b.at_standing %></td>
        <td><%= b.at_hitting %></td>
        <td><%= b.hit %></td>
        <td><%= b.run_batted_in %></td>
        <td><%= b.run %></td>
        <td><%= b.stolen_base %></td>
        <td><%= b.double %></td>
        <td><%= b.triple %></td>
        <td><%= b.homerun %></td>
        <td><%= b.strikeout %></td>
        <td><%= b.walk %></td>
        <td><%= b.hit_by_pitch %></td>
        <td><%= b.sacrifice_bunt %></td>
        <td><%= b.sacrifice_fly %></td>
        <td><%= b.double_play %></td>
        <td><%= b.opponent_error %></td>
        <td><%= b.fielding_error %></td>
       </tr>
      <% end %>
    </tbody>
    <tfoot class="thead-light">
      <tr>
        <th scope="col">背番号</th>
        <th scope="col">選手名</th>
        <th scope="col">出場</th>
        <th scope="col">打順</th>
        <th scope="col">守備位置</th>
        <th scope="col">打席</th>
        <th scope="col">打数</th>
        <th scope="col">安打</th>
        <th scope="col">打点</th>
        <th scope="col">得点</th>
        <th scope="col">盗塁</th>
        <th scope="col">二塁打</th>
        <th scope="col">三塁打</th>
        <th scope="col">本塁打</th>
        <th scope="col">三振</th>
        <th scope="col">四球</th>
        <th scope="col">死球</th>
        <th scope="col">犠打</th>
        <th scope="col">犠飛</th>
        <th scope="col">併殺</th>
        <th scope="col">敵失</th>
        <th scope="col">失策</th>
      </tr>
    </tfoot>
    </table>
    </div>
    <p class="text-muted">横にスクロールするとさらに細かい情報を確認できます</p>
  <% end %>

  <% if @pitching_stats.present? %>
    <div class="overflow-auto mt-4">
    <h4 class="mt-4">投手成績</h4>
    <table class="table text-center text-nowrap">
    <thead class="thead-light">
    <tr>
        <th scope="col">背番号</th>
        <th scope="col">選手名</th>
        <th scope="col">勝敗</th>
        <th scope="col" colspan="2">投球回</th>
        <th scope="col">失点</th>
        <th scope="col">自責点</th>
        <th scope="col">完投</th>
        <th scope="col">完封</th>
        <th scope="col">被安打</th>
        <th scope="col">被本塁打</th>
        <th scope="col">奪三振</th>
        <th scope="col">与四死球</th>
        <th scope="col">ボーク</th>
        <th scope="col">暴投</th>
        <th scope="col">登板順</th>
      </tr>
    </thead>
    <tbody>
      <% @pitching_stats.each do |p| %>
        <tr>
          <td><%= p.player.number %></td> 
          <td><%= link_to p.player.name, team_player_path(@team.team_url, p.player_id) %></td>
          <td><%= p.win_lose_or_save %></td>
          <td colspan="2"><%= p.inning %>回<%= p.part_of_inning %>/3</td>
          <td><%= p.runs_allowed %></td>
          <td><%= p.earned_run %></td>
          <td><%= p.complete_game %></td>
          <td><%= p.shutout %></td>
          <td><%= p.hit_allowed %></td>
          <td><%= p.homerun_allowed %></td>
          <td><%= p.strikeout %></td>
          <td><%= p.base_on_ball_or_hit_by_pitch %></td>
          <td><%= p.balk %></td>
          <td><%= p.wild_pitch %></td>
          <td><%= p.pitching_order %></td>
        </tr>
        <% end %>
    </tbody>
    <tfoot class="thead-light">
      <tr>
        <th scope="col">背番号</th>
        <th scope="col">選手名</th>
        <th scope="col">勝敗</th>
        <th scope="col" colspan="2">投球回</th>
        <th scope="col">失点</th>
        <th scope="col">自責点</th>
        <th scope="col">完投</th>
        <th scope="col">完封</th>
        <th scope="col">被安打</th>
        <th scope="col">被本塁打</th>
        <th scope="col">奪三振</th>
        <th scope="col">与四死球</th>
        <th scope="col">ボーク</th>
        <th scope="col">暴投</th>
        <th scope="col">登板順</th>
      </tr>
    </tfoot>
    </table>
    </div>
    <% end %>
  </div>

  <div class="row d-flex justify-content-around mt-3">
    <%= link_to "試合一覧へ戻る", team_games_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/games/update.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <h2>更新が完了しました。</h2>
  <div class="row d-flex justify-content-around">
    <%= link_to "試合結果詳細へ戻る", team_game_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>
</div>

<%= render 'shared/footer' %>