config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'
  devise_for :teams
  root "teams#top"
  get '/' => 'teams#show', as: :signin
  resources :teams, only: [:index, :show, :edit, :update, :destroy], param: :team_url do
    collection do
      get 'search'
    end
    member do
      get 'stat'
      get 'ranking'
    end
    resources :players
    resources :games do
      resources :batting_stats, only: [:new, :create]
      resources :pitching_stats, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
end

app/models/pitching_stat.rb
class PitchingStat < ApplicationRecord
  belongs_to :game
  belongs_to :player
end

app/controllers/pitching_stats_controller.rb
class PitchingStatsController < ApplicationController
  before_action :ensure_correct_team, only: [:new, :create]
  before_action :set_team, only: [:new, :create]
  before_action :set_players, only: [:new, :create]
  before_action :set_game, only: [:new, :create]

  def new
    @form = Form::PitchingStatCollection.new
  end

  def create
    @form = Form::PitchingStatCollection.new(pitching_stat_collection_params)
    if @form.save
      redirect_to team_game_path(@team.team_url, @game)
    else
      render :new
    end
  end

  private

  def pitching_stat_collection_params
    params.require(:form_pitching_stat_collection)
          .permit(pitching_stats_attributes: [:player_id, :pitching_order, :win_lose_or_save, :inning, :part_of_inning,
                                              :runs_allowed, :earned_run, :complete_game, :shutout, :hit_allowed,
                                              :homerun_allowed, :strikeout, :base_on_ball_or_hit_by_pitch,
                                              :balk, :wild_pitch, :game_id]).merge(game_id: params[:game_id])
  end

  def ensure_correct_team
    team = Team.find_by!(team_url: params[:team_team_url])
    redirect_to root_path if team != current_team
  end

  def set_team
    @team = Team.find_by!(team_url: params[:team_team_url])
  end

  def set_players
    @players = Player.where(team_id: @team.id).order(number: :asc)
  end

  def set_game
    @game = Game.find(params[:game_id])
  end
end

app/helpers/pitching_stats_helper.rb
module PitchingStatsHelper
end

app/views/pitching_stats/new.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">
  <h2>投手成績登録</h2>
  <p>成績を登録する選手にチェックを入れてください。</p>
  <p>横にスライドすることで詳細の情報を登録できます。</p>
  <%= form_with(model: @form, url: team_game_pitching_stats_path(@team.team_url), method: :post, local: true) do |form| %>
  <div class="overflow-auto">
  <table class="table text-center text-nowrap">
    <thead>
      <tr>
        <th></th>
        <th scope="col">背番号</th>
        <th scope="col">選手名</th>
        <th scope="col">登板順</th>
        <th scope="col">勝敗</th>
        <th scope="col" colspan="2">投球回</th>
        <th scope="col">失点</th>
        <th scope="col">自責点</th>
        <th scope="col">完投</th>
        <th scope="col">完封</th>
        <th scope="col">被安打</th>
        <th scope="col">被本塁打</th>
        <th scope="col">奪三振</th>
        <th scope="col">与四死球</th>
        <th scope="col">ボーク</th>
        <th scope="col">暴投</th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <%= form.fields_for :pitching_stats do |f| %>
      <tr>
        <td><%= f.check_box(:player_id, {}, player.id, nil) %></td>
        <td><%= player.number %></td> 
        <td><%= link_to player.name, team_player_path(@team.team_url, player) %></td>
        <td><%= f.number_field :pitching_order, style: "width: 40px;", min: 1 %></td>
        <td><%= f.select(:win_lose_or_save, ["勝", "負", "S"], {prompt: "--"} , {style: "height: 30px;"} ) %></td>
        <td><%= f.select(:inning, [0,1,2,3,4,5,6,7,8,9,10,11,12], {}, {style: "height: 30px;"} ) %> 回</td>
        <td><%= f.select(:part_of_inning, [0,1,2], {}, {style: "height: 30px;"} ) %> /3</td>
        <td><%= f.number_field :runs_allowed, style: "width: 40px;", min: 0 %></td>
        <td><%= f.number_field :earned_run, style: "width: 40px;", min: 0 %></td>
        <td><%= f.select(:complete_game, ["○"], {prompt: "--"} , {style: "height: 30px;"}) %></td>
        <td><%= f.select(:shutout, ["○"], {prompt: "--"} , {style: "height: 30px;"}) %></td>
        <td><%= f.number_field :hit_allowed, style: "width: 40px;", min: 0 %></td>
        <td><%= f.number_field :homerun_allowed, style: "width: 40px;", min: 0 %></td>
        <td><%= f.number_field :strikeout, style: "width: 40px;", min: 0 %></td>
        <td><%= f.number_field :base_on_ball_or_hit_by_pitch, style: "width: 40px;", min: 0 %></td>
        <td><%= f.number_field :balk, style: "width: 40px;", min: 0 %></td>
        <td><%= f.number_field :wild_pitch, style: "width: 40px;", min: 0 %></td>
        <td><%= f.hidden_field :game_id, value: @game.id %></td>
       </tr>
       <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th></th>
        <th scope="col">背番号</th>
        <th scope="col">選手名</th>
        <th scope="col">登板順</th>
        <th scope="col">勝敗</th>
        <th scope="col" colspan="2">投球回</th>
        <th scope="col">失点</th>
        <th scope="col">自責点</th>
        <th scope="col">完投</th>
        <th scope="col">完封</th>
        <th scope="col">被安打</th>
        <th scope="col">被本塁打</th>
        <th scope="col">奪三振</th>
        <th scope="col">与四死球</th>
        <th scope="col">ボーク</th>
        <th scope="col">暴投</th>
      </tr>
    </tfoot>
  </table>
  </div>

  <div class="actions my-3 d-flex justify-content-center">
   <%= form.submit "登録する", class: "col-4 mt-2 btn btn-primary" %>
  </div>

  <% end %>

  <div class="row d-flex justify-content-around">
    <%= link_to "試合結果詳細へ戻る", team_game_path(@team.team_url, @game), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>
  
</div>
<%= render 'shared/footer' %>