config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'
  devise_for :teams
  root "teams#top"
  get '/' => 'teams#show', as: :signin
  resources :teams, only: [:index, :show, :edit, :update, :destroy], param: :team_url do
    collection do
      get 'search'
    end
    member do
      get 'stat'
      get 'ranking'
    end
    resources :players
    resources :games do
      resources :batting_stats, only: [:new, :create]
      resources :pitching_stats, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :main_position
  belongs_to :team
  has_one_attached :image
  has_many :games, through: :batting_stats, through: :pitching_stats
  has_many :batting_stats
  has_many :pitching_stats

  validates :name, presence: true
  validates :main_position_id, presence: true, numericality: { other_than: 0, message: 'を選択してください' }
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update]
  before_action :set_team
  before_action :ensure_correct_team, except: [:index, :show]

  def index
    @players = Player.where(team_id: @team).order(number: :asc)
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to team_player_path(@team.team_url, @player.id)
    else
      render 'new'
    end
  end

  def show
    @batting_stats = BattingStat.all.where(player_id: @player.id)
    @batting_average = format('%.3f', @batting_stats.sum(:hit) / @batting_stats.sum(:at_hitting).to_f)
    @batting_on_base_percentage = format('%.3f', (@batting_stats.sum(:hit) + @batting_stats.sum(:walk) + @batting_stats.sum(:hit_by_pitch)) \
    / (@batting_stats.sum(:at_hitting) + @batting_stats.sum(:walk) + @batting_stats.sum(:hit_by_pitch) + @batting_stats.sum(:sacrifice_fly)).to_f)
    @batting_slugging_percentage = format('%.3f', (@batting_stats.sum(:hit) + (@batting_stats.sum(:double) * 2) + (@batting_stats.sum(:triple) * 3) \
    + (@batting_stats.sum(:homerun) * 4)) / @batting_stats.sum(:at_hitting).to_f)
    @batting_on_base_plus_slugging = format('%.3f', (@batting_stats.sum(:hit) + @batting_stats.sum(:walk) + @batting_stats.sum(:hit_by_pitch)) \
    / (@batting_stats.sum(:at_hitting) + @batting_stats.sum(:walk) + @batting_stats.sum(:hit_by_pitch) + @batting_stats.sum(:sacrifice_fly)).to_f \
    + (@batting_stats.sum(:hit) + (@batting_stats.sum(:double) * 2) + (@batting_stats.sum(:triple) * 3) + (@batting_stats.sum(:homerun) * 4)) / @batting_stats.sum(:at_hitting).to_f)

    @pitching_stats = PitchingStat.all.where(player_id: @player.id)
    @pitching_earned_run_average = format('%.2f', @pitching_stats.sum(:earned_run) * 7 / @pitching_stats.sum(:inning).to_f)
    @pitching_win_average = format('%.3f', @pitching_stats.where(win_lose_or_save: '勝').count / (@pitching_stats.where(win_lose_or_save: '勝').count + @pitching_stats.where(win_lose_or_save: '負').count).to_f)
    @pitching_strikeout_average = format('%.2f', @pitching_stats.sum(:strikeout) * 7 / @pitching_stats.sum(:inning).to_f)
  end

  def edit
  end

  def update
    if @player.update(player_params)
    else
      render 'edit'
    end
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
  end

  private

  def player_params
    params.require(:player).permit(:name, :sex, :birthday, :main_position_id, :number, :at_pitch, :at_bat,
                                   :player_post, :staff_post, :carrer, :promotion, :image, :batting, :power,
                                   :running, :throwing, :fielding, :speedball, :control, :stamina, :breakingball,
                                   :fielding_of_pitcher, sub_position: []).merge(team_id: current_team.id)
  end

  def set_player
    @player = Player.find(params[:id])
    gon.player = @player
  end

  def set_team
    @team = Team.find_by(team_url: params[:team_team_url])
  end

  def ensure_correct_team
    team = Team.find_by!(team_url: params[:team_team_url])
    redirect_to root_path if team != current_team
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/destroy.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <h2>削除が完了しました。</h2>
  <div class="row d-flex justify-content-around">
    <%= link_to "選手一覧へ戻る", team_players_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/players/index.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <div class="row d-flex justify-content-between">
    <h2>選手一覧</h2>
    <% if @team == current_team %>
      <%= link_to "選手新規登録", new_team_player_path(@team.team_url), class: "btn btn-info mb-2" %>
    <% end %>
  </div>
  
  <div class="row">
    <% @players.each do |player| %>
      <div class="media col-lg-6 p-3 position-relative border">
        <% if player.image.present? %>
          <%= link_to image_tag(player.image, class: "mr-3 rounded-circle", size: "100x100"), team_player_path(@team.team_url, player.id), class: "stretched-link" if player.image.attached? %>
        <% else %>
          <%= link_to image_tag('logo.jpg', class: "mr-3 rounded-circle", size: "100x100"), team_player_path(@team.team_url, player.id), class: "stretched-link" %>
        <% end %>
        <div class="media-body">
          <h5 class="pb-2 border-bottom">
            <%= player.number %>　<%= player.name %>
          </h5>
          <div class="row">
            <% case player.main_position_id %>
            <% when 1 %>
              <p class="mx-3 px-3 text-white rounded pitcher">
                <%= player.main_position.name %>
              </p>
            <% when 2 %>
              <p class="mx-3 px-3 text-white rounded catcher">
                <%= player.main_position.name %>
              </p>
            <% when 3 %>
              <p class="mx-3 px-3 text-white rounded infielder">
                <%= player.main_position.name %>
              </p>
            <% when 4 %>
              <p class="mx-3 px-3 text-white rounded outfielder">
                <%= player.main_position.name %>
              </p>
            <% else %>
              <p class="mx-3 px-3 text-white rounded staff">
                <%= player.main_position.name %>
              </p>
            <% end %>
            <p>
            （<%= player.at_pitch%>/<%= player.at_bat %>）
            </p>
          </div>
          <p class="text-muted mt-0">
            <%= player.player_post %> <%= player.staff_post %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row d-flex justify-content-around">
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/players/new.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">
  <h2>新規選手登録</h2>

  <%= form_with(model: @player, url: team_players_path(@team.team_url), local: true, method: :post) do |f| %>
    <%= render 'devise/shared/error_messages', resource: @player %>
  
    <div class="form-group row"> 
      <div class="col-sm-3">
        <%= f.label "選手名" %>
        <span class="ml-2 badge badge-danger">必須</span>
      </div>
      <%= f.text_field :name, class: "form-control col-sm-6" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "性別", class: "col-sm-3" %><br />
      <label class="form-check pr-2">
        <%= f.radio_button(:sex, '男') %> 男
      </label>
      <label class="form-check pr-2">
        <%= f.radio_button(:sex, '女') %> 女
      </label>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "生年月日", class: "col-sm-3" %><br />
      <%= f.date_field :birthday, class: "form-control col-sm-4", value: "1990-01-01" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <div class="col-sm-3">
        <%= f.label "メインポジション"%>
        <span class="ml-2 badge badge-danger">必須</span>
      </div>
      <%= f.collection_select(:main_position_id, MainPosition.all, :id, :name, {}, class: "col-sm-4 custom-select") %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "背番号", class: "col-sm-3" %><br />
      <%= f.number_field :number, class: "form-control col-sm-4", min: 0 %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "投打", class: "col-sm-3" %><br />
        <div class="form-check mr-4">
          <%= f.label "投", class: "mr-4" %>
          <label class="pr-2"><%= f.radio_button(:at_pitch, "右")%> 右</label>
          <label class="pr-2"><%= f.radio_button(:at_pitch, "左")%> 左</label>
          <label class="pr-2"><%= f.radio_button(:at_pitch, "両")%> 両</label>
          </div>
        <div class="form-check">
          <%= f.label "打", class: "mr-4" %>
          <label class="pr-2"><%= f.radio_button(:at_bat, "右")%> 右</label>
          <label class="pr-2"><%= f.radio_button(:at_bat, "左")%> 左</label>
          <label class="pr-2"><%= f.radio_button(:at_bat, "両")%> 両</label>
        </div>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <div class="col-sm-3">
        <%= f.label "サブポジション" %>
        <span class="ml-2 badge badge-secondary">複数選択可</span>
      </div>
      <% ["投手", "捕手", "内野手", "外野手"].each do |sub| %>
        <label class="form-check pr-2">
          <%= f.check_box :sub_position, {multiple: true}, sub, nil %>
          <%= sub %>
        </label>
      <% end %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "スキル", class: "col-sm-3"%>
      <table>
      <tr>
        <th>【野手】</th>
        <td>　0~100</td>
      </tr>
      <tr>
        <th>打撃</th>
        <td><%= f.number_field :batting, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>パワー</th>
        <td><%= f.number_field :power, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>走力</th>
        <td><%= f.number_field :running, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>肩力</th>
        <td><%= f.number_field :throwing, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>守備（野手）</th>
        <td><%= f.number_field :fielding, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      </table>
      <table class="ml-3">
      <tr>
        <th>【投手】</th>
        <td>　0~100</td>
      </tr>
      <tr>
        <th>球速</th>
        <td><%= f.number_field :speedball, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>コントロール</th>
        <td><%= f.number_field :control, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>スタミナ</th>
        <td><%= f.number_field :stamina, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>変化球</th>
        <td><%= f.number_field :breakingball, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      <tr>
        <th>守備（投手）</th>
        <td><%= f.number_field :fielding_of_pitcher, class: "ml-2 pl-2", max: 100, min: 0 %></td>
      </tr>
      </table>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "選手の役職", class: "col-sm-3" %><br />
      <%= f.text_area :player_post, class: "form-control col-sm-6", rows: 3, placeholder: "例）キャプテン、副キャプテン、渉外、用具など" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "スタッフの役職", class: "col-sm-3" %><br />
      <%= f.text_area :staff_post, class: "form-control col-sm-6", rows: 3, placeholder: "例）監督、コーチ、マネージャーなど" %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "野球歴", class: "col-sm-3" %><br />
      <%= f.text_area :carrer, class: "form-control col-sm-6", rows: 4 %>
    </div>
    <hr width="80%" align="left">
    <div class="form-group row">
      <%= f.label "PR・コメント", class: "col-sm-3 text-uppercase" %><br />
      <%= f.text_area :promotion, class: "form-control col-sm-6", rows: 4 %>
    </div>
    <hr width="80%" align="left">
    <div class="custom-file row mb-3">
      <%= f.label "選手画像", class: "col-sm-3" %>
      <%= f.file_field :image, id: "customFile" %>
    </div>
    <hr width="80%" align="left">
    <div class="actions my-3 d-flex justify-content-center">
      <%= f.submit "登録する", class: "col-8 btn btn-primary" %>
    </div>
  <% end %>

  <div class="row d-flex justify-content-around">
    <%= link_to "選手一覧へ戻る", team_players_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/players/show.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

    

  <div class="row  d-flex justify-content-center">
  <%# 選手画像の表示 %>
    <div class="col-lg-3 col-sm-4 text-center">
    <% if @player.image.present? %>
      <%= image_tag(@player.image, class: "m-2 rounded-circle", size: "150x150") if @player.image.attached? %>
    <% else %>
      <%= image_tag('logo.jpg', class: "m-2 rounded-circle", size: "150x150") %>
    <% end %>
    </div>
  <%# //選手画像の表示 %>

  <%# 選手名、背番号、ポジション、投打 %>
    <div class="col-lg-7 col-sm-6 text-center">
      <h2><%= @player.number %></h2>
      <div class="d-flex justify-content-center">
      <h3><%= @player.name %></h3>
      <% if @team == current_team %>
      <div class="btn-group">
        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="fas fa-pencil-alt fa-lg" style="color: darkblue"></span>
        </button>
        <div class="dropdown-menu">
          <%= link_to "編集", edit_team_player_path(@player.team.team_url), class: "dropdown-item" %>
          <%= link_to "削除", team_player_path(@player.team.team_url),class: "dropdown-item", method: :delete, data: {confirm: "本当に削除してもいいですか？"} %>
        </div>
      </div>
      <% end %>
      </div>
        <div class="progress">
          <div class="progress-bar bg-dark" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div class="pt-2">
          <%= @player.main_position.name %> ／ <%= @player.at_pitch %>／<%= @player.at_bat %>
        </div>
    </div>
  <%# //選手名、背番号、ポジション、投打 %>
  </div>

  <div class="row d-flex justify-content-center">
  <%# レーダーチャート（野手） %>
    <div class="col-lg-4 col-sm-4">
    <canvas id="radar-chart-batter" width="200" height="100" class="m-2"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
    </div>
  <%# レーダーチャート（野手） %>
  
  <%# レーダーチャート（投手） %>
    <div class="col-lg-4 col-sm-4">
    <canvas id="radar-chart-pitcher" width="200" height="100" class="m-2"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
    </div>
  <%# レーダーチャート（投手） %>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-sm-10 text-center">
      <table class="table table-bordered">
        <tr>
          <th scope="row" style="width: 200px;" class="table-dark">所属チーム</th>
          <td><%= @player.team.team_name %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">選手名</th>
          <td><%= @player.name %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">性別</th>
          <td><%= @player.sex %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">生年月日</th>
          <td><%= l(@player.birthday, format: :default) %>（<%= (Date.today.strftime("%Y%m%d").to_i - @player.birthday.strftime("%Y%m%d").to_i) / 10000 %>歳）</td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">メインポジション</th>
          <td id="main-position"><%= @player.main_position.name %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">背番号</th>
          <td><%= @player.number %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">投／打</th>
          <td><%= @player.at_pitch %> / <%= @player.at_bat %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">サブポジション</th>
          <td><%= @player.sub_position %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">選手の役職</th>
          <td><%= simple_format(@player.player_post) %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">スタッフの役職</th>
          <td><%= simple_format(@player.staff_post) %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">野球歴</th>
          <td><%= simple_format(@player.carrer) %></td>
        </tr>
        <tr>
          <th scope="row" class="table-dark">自己紹介</th>
          <td><%= simple_format(@player.promotion) %></td>
        </tr>
      </table>
    </div>
  </div>

  <hr>

  <div class="row d-flex justify-content-center">
    <div class="col-sm-10">
    <h3>個人成績</h3>
    <% if @batting_stats.present? %>
    <h4 class="mt-4">打者成績</h4>

    <div class="overflow-auto">
    <table class="table text-center text-nowrap">
    <thead class="thead-light">
      <tr>
        <th scope="col">試合数</th>
        <th scope="col">打席</th>
        <th scope="col">打数</th>
        <th scope="col">安打</th>
        <th scope="col">打率</th>
        <th scope="col">打点</th>
        <th scope="col">得点</th>
        <th scope="col">出塁率</th>
        <th scope="col">盗塁</th>
        <th scope="col">二塁打</th>
        <th scope="col">三塁打</th>
        <th scope="col">本塁打</th>
        <th scope="col">長打率</th>
        <th scope="col">OPS</th>
        <th scope="col">三振</th>
        <th scope="col">四球</th>
        <th scope="col">死球</th>
        <th scope="col">犠打</th>
        <th scope="col">犠飛</th>
        <th scope="col">併殺</th>
        <th scope="col">敵失</th>
        <th scope="col">失策</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @batting_stats.count %></td>
        <td><%= @batting_stats.sum(:at_standing) %></td>
        <td><%= @batting_stats.sum(:at_hitting) %></td>
        <td><%= @batting_stats.sum(:hit) %></td>
        <td><%= @batting_average %></td>
        <td><%= @batting_stats.sum(:run_batted_in) %></td>
        <td><%= @batting_stats.sum(:run) %></td>
        <td><%= @batting_on_base_percentage %></td>
        <td><%= @batting_stats.sum(:stolen_base) %></td>
        <td><%= @batting_stats.sum(:double) %></td>
        <td><%= @batting_stats.sum(:triple) %></td>
        <td><%= @batting_stats.sum(:homerun) %></td>
        <td><%= @batting_slugging_percentage %></td>
        <td><%= @batting_on_base_plus_slugging %></td>
        <td><%= @batting_stats.sum(:strikeout) %></td>
        <td><%= @batting_stats.sum(:walk) %></td>
        <td><%= @batting_stats.sum(:hit_by_pitch) %></td>
        <td><%= @batting_stats.sum(:sacrifice_bunt) %></td>
        <td><%= @batting_stats.sum(:sacrifice_fly) %></td>
        <td><%= @batting_stats.sum(:double_play) %></td>
        <td><%= @batting_stats.sum(:opponent_error) %></td>
        <td><%= @batting_stats.sum(:fielding_error) %></td>
       </tr>
    </tbody>
    <tfoot class="thead-light">
      <tr>
        <th scope="col">試合数</th>
        <th scope="col">打席</th>
        <th scope="col">打数</th>
        <th scope="col">安打</th>
        <th scope="col">打率</th>
        <th scope="col">打点</th>
        <th scope="col">得点</th>
        <th scope="col">出塁率</th>
        <th scope="col">盗塁</th>
        <th scope="col">二塁打</th>
        <th scope="col">三塁打</th>
        <th scope="col">本塁打</th>
        <th scope="col">長打率</th>
        <th scope="col">OPS</th>
        <th scope="col">三振</th>
        <th scope="col">四球</th>
        <th scope="col">死球</th>
        <th scope="col">犠打</th>
        <th scope="col">犠飛</th>
        <th scope="col">併殺</th>
        <th scope="col">敵失</th>
        <th scope="col">失策</th>
      </tr>
    </tfoot>
    </table>
    </div>
    <p class="text-muted">横にスクロールするとさらに細かい情報を確認できます</p>
  <% end %>

  <hr>
  
  <% if @pitching_stats.present?%>
  <h4 class="mt-4">投手成績</h4>
  <div class="overflow-auto">
    <table class="table text-center text-nowrap">
    <thead class="thead-light">
    <tr>
        <th scope="col">試合数</th>
        <th scope="col">勝</th>
        <th scope="col">負</th>
        <th scope="col">S</th>
        <th scope="col" colspan="2">投球回</th>
        <th scope="col">失点</th>
        <th scope="col">自責点</th>
        <th scope="col">防御率</th>
        <th scope="col">勝率</th>
        <th scope="col">完投</th>
        <th scope="col">完封</th>
        <th scope="col">被安打</th>
        <th scope="col">被本塁打</th>
        <th scope="col">奪三振</th>
        <th scope="col">奪三振率</th>
        <th scope="col">与四死球</th>
        <th scope="col">ボーク</th>
        <th scope="col">暴投</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @pitching_stats.count %></td>
          <td><%= @pitching_stats.where(win_lose_or_save: "勝").count %></td>
          <td><%= @pitching_stats.where(win_lose_or_save: "負").count %></td>
          <td><%= @pitching_stats.where(win_lose_or_save: "S").count %></td>
          <td colspan="2"><%= @pitching_stats.sum(:inning) + ( @pitching_stats.sum(:part_of_inning) / 3 ) %>回<%= @pitching_stats.sum(:part_of_inning) % 3 %>/3</td>
          <td><%= @pitching_stats.sum(:runs_allowed) %></td>
          <td><%= @pitching_stats.sum(:earned_run) %></td>
          <td><%= @pitching_earned_run_average %></td>
          <td><%= @pitching_win_average %></td>
          <td><%= @pitching_stats.where(complete_game: "○").count %></td>
          <td><%= @pitching_stats.where(shutout: "○").count %></td>
          <td><%= @pitching_stats.sum(:hit_allowed) %></td>
          <td><%= @pitching_stats.sum(:homerun_allowed) %></td>
          <td><%= @pitching_stats.sum(:strikeout) %></td>
          <td><%= @pitching_strikeout_average %></td>
          <td><%= @pitching_stats.sum(:base_on_ball_or_hit_by_pitch) %></td>
          <td><%= @pitching_stats.sum(:balk) %></td>
          <td><%= @pitching_stats.sum(:wild_pitch) %></td>
        </tr>
    </tbody>
    <tfoot class="thead-light">
      <tr>
        <th scope="col">試合数</th>
        <th scope="col">勝</th>
        <th scope="col">負</th>
        <th scope="col">S</th>
        <th scope="col" colspan="2">投球回</th>
        <th scope="col">失点</th>
        <th scope="col">自責点</th>
        <th scope="col">防御率</th>
        <th scope="col">勝率</th>
        <th scope="col">完投</th>
        <th scope="col">完封</th>
        <th scope="col">被安打</th>
        <th scope="col">被本塁打</th>
        <th scope="col">奪三振</th>
        <th scope="col">奪三振率</th>
        <th scope="col">与四死球</th>
        <th scope="col">ボーク</th>
        <th scope="col">暴投</th>
      </tr>
    </tfoot>
    </table>
    </div>
    <p class="text-muted">横にスクロールするとさらに細かい情報を確認できます</p>
    <% end %>
    </div>
  </div>
    
  <div class="row d-flex justify-content-around mt-3">
    <%= link_to "選手一覧へ戻る", team_players_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>
  
</div>

<%= render 'shared/footer' %>

app/views/players/update.html.erb
<%= render 'shared/header' %>

<div class="container mt-3">

  <h2>更新が完了しました。</h2>
  <div class="row d-flex justify-content-around">
    <%= link_to "選手詳細へ戻る", team_player_path(@team.team_url), class: "btn btn-outline-success col-sm-3 m-2" %>
    <%= link_to "チームページへ戻る", team_path(@team.team_url), class: "btn btn-outline-secondary col-sm-3 m-2" %>
    <%= link_to "トップページへ戻る", root_path, class: "btn btn-outline-info col-sm-3 m-2" %>
  </div>
</div>

<%= render 'shared/footer' %>